---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-pvc
  namespace: cs-ns
  labels: 
    app: cs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources: 
    requests:
      storage: 1Gi

