# for illustration purpose
# should be added in gitignore
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: bgg-cm
  namespace: bggns
  labels:
    app: bgg
    name: bgg-cm
data: 
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata: 
  name: bgg-secret
  namespace: bggns
  labels:
    app: bgg
    name: bgg-secret
data: 
  BGG_DB_PASSWORD: changeit