volumes: 
  dc-data:
  
networks:
  dc-net:

services:
  dc-db:
    image: stackupiss/northwind-db:v1
    volumes:
    - dc-data:/var/lib/mysql 
    networks:
    - dc-net

  dc-app:
    image: stackupiss/northwind-app:v1
    networks:
    - dc-net
    environment: 
    - DB_HOST=dc-db
    - DB_USER=root
    - DB_PASSWORD=changeit
    ports:
    - 9000-9090:3000 # any available port from 9000 to 9090 will bind to 3000


## command to run
# docker compose up -d (-d = detach / without = run all commands in foreground) 
# docker compose down (manage all except volumes - manual cleanup required)
